[package]
name = "vk_method"
description = "VK Standart Method"
version = "0.1.3"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ijson = "0.1"
serde = "1.0"
serde_json = "1.0"
